"""Generate TypeScript declarations from the API's OpenAPI document.

The frontend validates responses with Zod and asserts at compile time that each Zod schema is a
projection of these generated types, so backend contract changes surface as TypeScript errors.
Only the JSON Schema subset that Pydantic and FastAPI emit is supported; anything else fails
loudly instead of being guessed.
"""

import json
import re
from collections.abc import Mapping, Sequence
from typing import cast

JsonObject = Mapping[str, object]

HEADER = "// GENERATED by `ffia schemas export` from schemas/openapi.json. Do not edit by hand.\n"
_IDENT = re.compile(r"[^A-Za-z0-9_]")


class UnsupportedSchemaError(ValueError):
    """Raised for JSON Schema constructs the generator does not translate."""


def type_name(schema_name: str) -> str:
    """Return a valid TypeScript identifier for an OpenAPI component name."""
    name = _IDENT.sub("_", schema_name)
    return name if not name[0].isdigit() else f"_{name}"


def _as_object(value: object, where: str) -> JsonObject:
    if not isinstance(value, Mapping):
        raise UnsupportedSchemaError(f"{where}: expected an object")
    return cast("JsonObject", value)


def _as_list(value: object, where: str) -> Sequence[object]:
    if not isinstance(value, list):
        raise UnsupportedSchemaError(f"{where}: expected a list")
    return cast("list[object]", value)


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float, str)):
        return json.dumps(value)
    raise UnsupportedSchemaError(f"unsupported literal {value!r}")


def _union(parts: Sequence[str]) -> str:
    unique = list(dict.fromkeys(parts))
    return unique[0] if len(unique) == 1 else " | ".join(unique)


def _wrap(expression: str) -> str:
    needs_parens = " | " in expression or expression.startswith("readonly ")
    return f"({expression})" if needs_parens else expression


_SCALARS = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _render_composite(schema: JsonObject, where: str) -> str | None:
    """Render ``$ref``, ``const``, ``enum`` and combinators; return None for plain types."""
    if "$ref" in schema:
        return type_name(str(schema["$ref"]).rsplit("/", 1)[-1])
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return _union([_literal(v) for v in _as_list(schema["enum"], where)])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            options = _as_list(schema[key], where)
            return _union([render_type(_as_object(o, where), where) for o in options])
    if "allOf" in schema:
        parts = _as_list(schema["allOf"], where)
        return " & ".join(_wrap(render_type(_as_object(p, where), where)) for p in parts)
    return None


def render_type(schema: JsonObject, where: str = "schema") -> str:
    """Render one JSON Schema as a TypeScript type expression."""
    composite = _render_composite(schema, where)
    if composite is not None:
        return composite
    kind = schema.get("type")
    if isinstance(kind, list):
        kinds = cast("list[object]", kind)
        return _union([render_type({**schema, "type": k}, where) for k in kinds])
    if kind is None:
        return "unknown"
    if kind == "array":
        return _render_array(schema, where)
    if kind == "object":
        return _render_object(schema, where)
    if isinstance(kind, str) and kind in _SCALARS:
        return _SCALARS[kind]
    raise UnsupportedSchemaError(f"{where}: unsupported type {kind!r}")


def _render_array(schema: JsonObject, where: str) -> str:
    if "prefixItems" in schema:
        items = _as_list(schema["prefixItems"], where)
        return f"readonly [{', '.join(render_type(_as_object(i, where), where) for i in items)}]"
    items_schema = schema.get("items")
    item = (
        render_type(_as_object(items_schema, where), where)
        if items_schema is not None
        else "unknown"
    )
    return f"readonly {_wrap(item)}[]"


def _render_object(schema: JsonObject, where: str, indent: str = "") -> str:
    properties = schema.get("properties")
    if properties is None:
        extra = schema.get("additionalProperties")
        # additionalProperties may be a schema, True/False, or absent.
        value = (
            "unknown"
            if extra is None or isinstance(extra, bool)
            else render_type(_as_object(extra, where), where)
        )
        return f"Readonly<Record<string, {value}>>"
    required = {str(r) for r in _as_list(schema.get("required", []), where)}
    lines = ["{"]
    for name, prop in _as_object(properties, where).items():
        optional = "" if name in required else "?"
        key = name if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) else json.dumps(name)
        rendered = render_type(_as_object(prop, f"{where}.{name}"), f"{where}.{name}")
        lines.append(f"{indent}  readonly {key}{optional}: {rendered};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def render_typescript(openapi: JsonObject) -> str:
    """Render every component schema of an OpenAPI document as a TypeScript declaration."""
    components = _as_object(openapi.get("components", {}), "components")
    schemas = _as_object(components.get("schemas", {}), "components.schemas")
    blocks = [HEADER]
    for raw_name in sorted(schemas):
        schema = _as_object(schemas[raw_name], raw_name)
        name = type_name(raw_name)
        description = schema.get("description") or schema.get("title")
        summary = str(description).splitlines()[0].replace("*/", "* /") if description else ""
        doc = f"/** {summary} */\n" if summary else ""
        if schema.get("type") == "object" and "properties" in schema:
            blocks.append(f"{doc}export interface {name} {_render_object(schema, raw_name)}\n")
        else:
            blocks.append(f"{doc}export type {name} = {render_type(schema, raw_name)};\n")
    return "\n".join(blocks)
