# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # MCP_02_Silver: typed, row-preserving Silver tables
#
# **Synthetic data only.** Use-Case Guide HC-01 profile: seven CSV sources whose row counts and structural quirks match the guide's documented baseline.
#
# Applies explicit types, date parsing, bands, condition mapping and data-quality flags. Every Silver
# table keeps its Bronze row count. Diagnostics must match the counts the generator injected.
#
# - Attach the default lakehouse (for example `healthcare_lakehouse`) before running. No workspace or
#   lakehouse ID is stored in this definition.
# - Generated by `ffia notebooks render` from the same SQL the offline build runs on DuckDB. Do not
#   hand-edit; change the SQL and re-render.
# - A run in the portal or editor is not an MCP job. Evidence is the printed checks and read-back counts.

# PARAMETERS CELL ********************

TABLE_FORMAT = "delta"
EXPECTED_SILVER_ROWS = {
    "silver_claims": 1025,
    "silver_clinical_notes": 150,
    "silver_conditions": 428,
    "silver_encounters": 1025,
    "silver_medications": 643,
    "silver_patients": 200,
    "silver_vitals": 4299
}
EXPECTED_DIAGNOSTICS = {
    "blank_total_charges": 5,
    "conditions_with_blank_encounter_id": 428,
    "encounter_chronology_violations": 0,
    "length_of_stay_mismatches": 4,
    "medication_chronology_violations": 3,
    "notes_with_embedded_newline": 0,
    "notes_with_literal_newline": 56,
    "out_of_range_vitals": 6,
    "overlapping_encounters": 3,
    "zero_claim_amounts": 3
}
DIAGNOSTICS = {
    "blank_total_charges": [
        "silver_encounters",
        "total_charges IS NULL"
    ],
    "conditions_with_blank_encounter_id": [
        "silver_conditions",
        "encounter_id IS NULL"
    ],
    "encounter_chronology_violations": [
        "silver_encounters",
        "NOT is_chronology_valid"
    ],
    "length_of_stay_mismatches": [
        "silver_encounters",
        "NOT is_los_consistent"
    ],
    "medication_chronology_violations": [
        "silver_medications",
        "NOT is_chronology_valid"
    ],
    "notes_with_embedded_newline": [
        "silver_clinical_notes",
        "has_embedded_newline"
    ],
    "notes_with_literal_newline": [
        "silver_clinical_notes",
        "has_literal_newline_sequence"
    ],
    "out_of_range_vitals": [
        "silver_vitals",
        "is_out_of_range"
    ],
    "overlapping_encounters": [
        "silver_encounters",
        "overlaps_prior_encounter"
    ],
    "zero_claim_amounts": [
        "silver_claims",
        "claim_amount = 0"
    ]
}
KEYS = {
    "silver_claims": [
        "claim_id"
    ],
    "silver_clinical_notes": [
        "note_id"
    ],
    "silver_conditions": [
        "condition_id"
    ],
    "silver_encounters": [
        "encounter_id"
    ],
    "silver_medications": [
        "medication_id"
    ],
    "silver_patients": [
        "patient_id"
    ],
    "silver_vitals": [
        "vital_id"
    ]
}

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

from pyspark.sql import functions as F

CHECKS: list[tuple[str, bool, str]] = []


def check(name: str, passed: bool, detail: str) -> None:
    """Record and print one validation result."""
    CHECKS.append((name, passed, detail))
    print(f"[{'PASS' if passed else 'FAIL'}] {name}: {detail}")


def write_table(df, name: str) -> int:
    """Overwrite one table and return the persisted (read-back) row count."""
    (
        df.write.format(TABLE_FORMAT)
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(name)
    )
    return spark.table(name).count()


def scalar(sql: str):
    """Return the single value of a one-row, one-column query."""
    return spark.sql(sql).collect()[0][0]


def key_check(table: str, keys: list[str]) -> None:
    """Keys are populated and unique."""
    cols = ", ".join(f"`{k}`" for k in keys)
    populated = " AND ".join(f"`{k}` IS NOT NULL" for k in keys)
    total = scalar(f"SELECT count(*) FROM `{table}`")
    distinct = scalar(f"SELECT count(DISTINCT {cols}) FROM `{table}` WHERE {populated}")
    filled = scalar(f"SELECT count(*) FROM `{table}` WHERE {populated}")
    check(
        f"{table}: key ({', '.join(keys)}) populated and unique",
        total == distinct == filled,
        f"rows {total}, distinct keys {distinct}, populated keys {filled}",
    )


def finish() -> None:
    """Stop the run if any check failed, so a failed layer is never reported as built."""
    failed = [name for name, passed, _ in CHECKS if not passed]
    if failed:
        raise AssertionError(f"{len(failed)} check(s) failed: {failed}")
    print(f"All {len(CHECKS)} checks passed.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

SQL = {}
SQL["silver_patients"] = """
-- Typed, conformed patients. Age bands and risk categories are synthetic analytical definitions.
WITH typed AS (
    SELECT
        patient_id,
        first_name,
        last_name,
        CAST(try_to_timestamp(date_of_birth, 'yyyy-MM-dd') AS DATE) AS date_of_birth,
        TRY_CAST(age AS INTEGER) AS age,
        gender,
        race,
        zip_code,
        city,
        state,
        insurance_type,
        primary_care_provider,
        TRY_CAST(risk_score AS DECIMAL(4, 2)) AS risk_score
    FROM bronze_patients
)
SELECT
    *,
    CASE
        WHEN age IS NULL THEN NULL
        WHEN age < 18 THEN '0-17'
        WHEN age < 40 THEN '18-39'
        WHEN age < 65 THEN '40-64'
        ELSE '65+'
    END AS age_band,
    CASE
        WHEN risk_score IS NULL THEN NULL
        WHEN risk_score >= 0.70 THEN 'High'
        WHEN risk_score >= 0.40 THEN 'Moderate'
        ELSE 'Low'
    END AS risk_category
FROM typed
"""

SQL["silver_encounters"] = """
-- Typed encounters with calendar fields, LOS bands and data-quality flags.
-- Uses the actual discharge_date; never approximates discharge as encounter_date + LOS.
WITH typed AS (
    SELECT
        encounter_id,
        patient_id,
        CAST(try_to_timestamp(encounter_date, 'yyyy-MM-dd') AS DATE) AS encounter_date,
        encounter_time,
        CAST(try_to_timestamp(discharge_date, 'yyyy-MM-dd') AS DATE) AS discharge_date,
        encounter_type,
        facility_id,
        facility_name,
        department,
        primary_diagnosis_code,
        primary_diagnosis_description,
        attending_provider,
        discharge_disposition,
        TRY_CAST(length_of_stay_days AS INTEGER) AS length_of_stay_days,
        TRY_CAST(total_charges AS DECIMAL(12, 2)) AS total_charges
    FROM bronze_encounters
)
SELECT
    *,
    year(encounter_date) AS encounter_year,
    quarter(encounter_date) AS encounter_quarter,
    month(encounter_date) AS encounter_month,
    CASE
        WHEN length_of_stay_days IS NULL THEN NULL
        WHEN length_of_stay_days = 0 THEN '0 days'
        WHEN length_of_stay_days <= 2 THEN '1-2 days'
        WHEN length_of_stay_days <= 5 THEN '3-5 days'
        ELSE '6+ days'
    END AS los_band,
    encounter_type = 'Inpatient' AS is_inpatient,
    encounter_type = 'ED' AS is_ed,
    discharge_date >= encounter_date AS is_chronology_valid,
    length_of_stay_days = datediff(discharge_date, encounter_date) AS is_los_consistent,
    coalesce(
        encounter_date < max(discharge_date) OVER (
            PARTITION BY patient_id
            ORDER BY encounter_date, encounter_id
            ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING
        ),
        false
    ) AS overlaps_prior_encounter
FROM typed
"""

SQL["silver_conditions"] = """
-- Patient-level problem list. encounter_id is blank in the source and is retained as NULL;
-- condition records are never linked to encounters artificially.
SELECT
    condition_id,
    patient_id,
    encounter_id,
    condition_code,
    condition_description,
    condition_type,
    CAST(try_to_timestamp(date_diagnosed, 'yyyy-MM-dd') AS DATE) AS date_diagnosed,
    status,
    condition_type = 'Chronic' AS is_chronic,
    CASE
        WHEN startswith(condition_code, 'E11') THEN 'Diabetes'
        WHEN startswith(condition_code, 'I10') THEN 'Hypertension'
        WHEN startswith(condition_code, 'I50') THEN 'Heart Failure'
        WHEN startswith(condition_code, 'J44') THEN 'COPD'
        WHEN startswith(condition_code, 'N18') THEN 'Chronic Kidney Disease'
        WHEN startswith(condition_code, 'E78') THEN 'Hyperlipidemia'
        WHEN startswith(condition_code, 'J45') THEN 'Asthma'
        WHEN startswith(condition_code, 'E66') THEN 'Obesity'
        WHEN startswith(condition_code, 'M17') THEN 'Osteoarthritis'
        ELSE 'Unmapped'
    END AS condition_category
FROM bronze_conditions
"""

SQL["silver_claims"] = """
-- Claims with decimal money. is_denied means claim_status = 'Denied' only;
-- 'Paid on Appeal' stays a separate status. payment_ratio is guarded against zero claim_amount.
WITH typed AS (
    SELECT
        claim_id,
        patient_id,
        encounter_id,
        CAST(try_to_timestamp(claim_date, 'yyyy-MM-dd') AS DATE) AS claim_date,
        payer,
        payer_type,
        TRY_CAST(claim_amount AS DECIMAL(12, 2)) AS claim_amount,
        TRY_CAST(paid_amount AS DECIMAL(12, 2)) AS paid_amount,
        TRY_CAST(denied_amount AS DECIMAL(12, 2)) AS denied_amount,
        TRY_CAST(patient_responsibility AS DECIMAL(12, 2)) AS patient_responsibility,
        denial_reason,
        claim_status,
        TRY_CAST(days_to_payment AS INTEGER) AS days_to_payment
    FROM bronze_claims
)
SELECT
    *,
    claim_status = 'Denied' AS is_denied,
    CASE WHEN claim_amount > 0 THEN round(paid_amount / claim_amount, 4) END AS payment_ratio
FROM typed
"""

SQL["silver_vitals"] = """
-- Numeric vital-sign observations with a range check. The flag reports parsing/range issues only;
-- it never labels a clinical condition.
WITH typed AS (
    SELECT
        vital_id,
        patient_id,
        encounter_id,
        facility_name,
        department,
        try_to_timestamp(`timestamp`, 'yyyy-MM-dd HH:mm:ss') AS vital_timestamp,
        TRY_CAST(heart_rate AS INTEGER) AS heart_rate,
        TRY_CAST(systolic_bp AS INTEGER) AS systolic_bp,
        TRY_CAST(diastolic_bp AS INTEGER) AS diastolic_bp,
        TRY_CAST(temperature_f AS DECIMAL(4, 1)) AS temperature_f,
        TRY_CAST(respiratory_rate AS INTEGER) AS respiratory_rate,
        TRY_CAST(spo2_percent AS INTEGER) AS spo2_percent,
        TRY_CAST(pain_level AS INTEGER) AS pain_level
    FROM bronze_vitals
)
SELECT
    *,
    NOT (
        coalesce(heart_rate BETWEEN 20 AND 250, true)
        AND coalesce(systolic_bp BETWEEN 50 AND 260, true)
        AND coalesce(diastolic_bp BETWEEN 20 AND 160, true)
        AND coalesce(temperature_f BETWEEN 90 AND 110, true)
        AND coalesce(respiratory_rate BETWEEN 4 AND 60, true)
        AND coalesce(spo2_percent BETWEEN 50 AND 100, true)
        AND coalesce(pain_level BETWEEN 0 AND 10, true)
    ) AS is_out_of_range
FROM typed
"""

SQL["silver_medications"] = """
-- Medication orders at order grain with a chronology check (end_date before start_date).
WITH typed AS (
    SELECT
        medication_id,
        patient_id,
        encounter_id,
        medication_name,
        medication_class,
        dosage,
        frequency,
        prescriber,
        CAST(try_to_timestamp(start_date, 'yyyy-MM-dd') AS DATE) AS start_date,
        CAST(try_to_timestamp(end_date, 'yyyy-MM-dd') AS DATE) AS end_date,
        status
    FROM bronze_medications
)
SELECT
    *,
    end_date IS NULL OR end_date >= start_date AS is_chronology_valid
FROM typed
"""

SQL["silver_clinical_notes"] = """
-- Notes with original note_text preserved byte-for-byte. Literal backslash-n sequences are
-- flagged, not converted; any display conversion must be a separate, explicit step.
SELECT
    note_id,
    patient_id,
    encounter_id,
    CAST(try_to_timestamp(note_date, 'yyyy-MM-dd') AS DATE) AS note_date,
    note_type,
    provider,
    note_text,
    instr(note_text, chr(92) || 'n') > 0 AS has_literal_newline_sequence,
    instr(note_text, chr(10)) > 0 AS has_embedded_newline
FROM bronze_clinical_notes
"""

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

for name, sql in SQL.items():
    persisted = write_table(spark.sql(sql), name)
    expected_rows = EXPECTED_SILVER_ROWS[name]
    check(f"{name}: rows equal baseline", persisted == expected_rows, f"{persisted} (baseline {expected_rows})")
    key_check(name, KEYS[name])
    bronze = name.replace("silver_", "bronze_", 1)
    if spark.catalog.tableExists(bronze):
        source = spark.table(bronze).count()
        check(f"{name}: row count preserved from {bronze}", persisted == source, f"silver {persisted}, bronze {source}")

for name, (table, predicate) in DIAGNOSTICS.items():
    found = scalar(f"SELECT count(*) FROM `{table}` WHERE {predicate}")
    expected_count = EXPECTED_DIAGNOSTICS[name]
    check(f"diagnostic {name}", found == expected_count, f"found {found}, expected {expected_count}")

finish()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
