# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # MCP_03_Gold: reviewed grains, dimensions and reconciliation
#
# **Synthetic data only.** Use-Case Guide HC-01 profile: seven CSV sources whose row counts and structural quirks match the guide's documented baseline.
#
# Builds the Gold tables and physical dimensions, then checks keys, row preservation, missing
# dimension keys and financial reconciliation with Silver. Prints the readmission numerator and
# denominator.
#
# - Attach the default lakehouse (for example `healthcare_lakehouse`) before running. No workspace or
#   lakehouse ID is stored in this definition.
# - Generated by `ffia notebooks render` from the same SQL the offline build runs on DuckDB. Do not
#   hand-edit; change the SQL and re-render.
# - A run in the portal or editor is not an MCP job. Evidence is the printed checks and read-back counts.

# PARAMETERS CELL ********************

TABLE_FORMAT = "delta"
EXPECTED_GOLD_ROWS = {
    "dim_date": 742,
    "dim_facility": 5,
    "dim_patient": 200,
    "dim_payer": 5,
    "gold_alos": 24,
    "gold_ed_utilization": 151,
    "gold_encounter_summary": 1025,
    "gold_financial": 1025,
    "gold_population_health": 200,
    "gold_readmissions": 217
}
EXPECTED_RECONCILIATION = {
    "claim_amount_minus_recorded_charges": 2914.3,
    "gold_claim_amount_total": 4838293.33,
    "gold_paid_amount_total": 2870467.63,
    "gold_total_charges": 4835379.03,
    "silver_claim_amount_total": 4838293.33,
    "silver_paid_amount_total": 2870467.63,
    "silver_total_charges": 4835379.03
}
STAGING = []
KEYS = {
    "dim_date": [
        "date"
    ],
    "dim_facility": [
        "facility_id"
    ],
    "dim_patient": [
        "patient_id"
    ],
    "dim_payer": [
        "payer_key"
    ],
    "gold_alos": [
        "primary_diagnosis_code",
        "facility_id"
    ],
    "gold_ed_utilization": [
        "patient_id",
        "year"
    ],
    "gold_encounter_summary": [
        "encounter_id"
    ],
    "gold_financial": [
        "claim_id"
    ],
    "gold_population_health": [
        "patient_id"
    ],
    "gold_readmissions": [
        "index_encounter_id"
    ]
}
ROW_PRESERVATION = [
    [
        "gold_encounter_summary",
        "silver_encounters"
    ],
    [
        "gold_financial",
        "silver_claims"
    ],
    [
        "gold_population_health",
        "silver_patients"
    ],
    [
        "dim_patient",
        "silver_patients"
    ]
]
RELATIONSHIPS = [
    [
        "gold_encounter_summary",
        "patient_id",
        "dim_patient",
        "patient_id"
    ],
    [
        "gold_financial",
        "patient_id",
        "dim_patient",
        "patient_id"
    ],
    [
        "gold_readmissions",
        "patient_id",
        "dim_patient",
        "patient_id"
    ],
    [
        "gold_encounter_summary",
        "facility_id",
        "dim_facility",
        "facility_id"
    ],
    [
        "gold_financial",
        "facility_id",
        "dim_facility",
        "facility_id"
    ],
    [
        "gold_readmissions",
        "facility_id",
        "dim_facility",
        "facility_id"
    ],
    [
        "gold_financial",
        "payer_key",
        "dim_payer",
        "payer_key"
    ],
    [
        "gold_encounter_summary",
        "encounter_date",
        "dim_date",
        "date"
    ],
    [
        "gold_financial",
        "claim_date",
        "dim_date",
        "date"
    ],
    [
        "gold_readmissions",
        "index_discharge_date",
        "dim_date",
        "date"
    ]
]
ENCOUNTERS, CLAIMS = "gold_encounter_summary", "gold_financial"
READMISSIONS = "gold_readmissions"

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

from pyspark.sql import functions as F

CHECKS: list[tuple[str, bool, str]] = []


def check(name: str, passed: bool, detail: str) -> None:
    """Record and print one validation result."""
    CHECKS.append((name, passed, detail))
    print(f"[{'PASS' if passed else 'FAIL'}] {name}: {detail}")


def write_table(df, name: str) -> int:
    """Overwrite one table and return the persisted (read-back) row count."""
    (
        df.write.format(TABLE_FORMAT)
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(name)
    )
    return spark.table(name).count()


def scalar(sql: str):
    """Return the single value of a one-row, one-column query."""
    return spark.sql(sql).collect()[0][0]


def key_check(table: str, keys: list[str]) -> None:
    """Keys are populated and unique."""
    cols = ", ".join(f"`{k}`" for k in keys)
    populated = " AND ".join(f"`{k}` IS NOT NULL" for k in keys)
    total = scalar(f"SELECT count(*) FROM `{table}`")
    distinct = scalar(f"SELECT count(DISTINCT {cols}) FROM `{table}` WHERE {populated}")
    filled = scalar(f"SELECT count(*) FROM `{table}` WHERE {populated}")
    check(
        f"{table}: key ({', '.join(keys)}) populated and unique",
        total == distinct == filled,
        f"rows {total}, distinct keys {distinct}, populated keys {filled}",
    )


def finish() -> None:
    """Stop the run if any check failed, so a failed layer is never reported as built."""
    failed = [name for name, passed, _ in CHECKS if not passed]
    if failed:
        raise AssertionError(f"{len(failed)} check(s) failed: {failed}")
    print(f"All {len(CHECKS)} checks passed.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

SQL = {}
SQL["dim_date"] = """
-- One row per calendar date covering every encounter, discharge and claim date.
WITH bounds AS (
    SELECT
        least(
            (SELECT min(encounter_date) FROM silver_encounters),
            (SELECT min(claim_date) FROM silver_claims)
        ) AS first_date,
        greatest(
            (SELECT max(discharge_date) FROM silver_encounters),
            (SELECT max(claim_date) FROM silver_claims)
        ) AS last_date
),
spine AS (
    SELECT
        explode(sequence(CAST(first_date AS DATE), CAST(last_date AS DATE), INTERVAL 1 DAY)) AS calendar_date
    FROM bounds
)
SELECT
    calendar_date AS `date`,
    year(calendar_date) AS `year`,
    quarter(calendar_date) AS `quarter`,
    month(calendar_date) AS `month`,
    date_format(calendar_date, 'MMMM') AS month_name,
    date_format(calendar_date, 'yyyy-MM') AS year_month,
    ((dayofweek(calendar_date) + 5) % 7 + 1) AS day_of_week,
    date_format(calendar_date, 'EEEE') AS day_name,
    ((dayofweek(calendar_date) + 5) % 7 + 1) IN (6, 7) AS is_weekend
FROM spine
ORDER BY calendar_date
"""

SQL["dim_facility"] = """
-- Facility dimension derived from encounters (this profile has no facility master).
SELECT DISTINCT facility_id, facility_name
FROM silver_encounters
"""

SQL["dim_payer"] = """
-- Payer dimension with a surrogate payer_key (this profile has no payer master).
SELECT
    'PYR-' || lpad(CAST(row_number() OVER (ORDER BY payer, payer_type) AS STRING), 2, '0') AS payer_key,
    payer,
    payer_type
FROM (SELECT DISTINCT payer, payer_type FROM silver_claims)
"""

SQL["gold_population_health"] = """
-- One row per patient, INCLUDING patients with zero conditions. Condition flags count Active
-- conditions in each reviewed category. Multimorbidity groups and risk categories are synthetic
-- analytical definitions.
WITH conditions AS (
    SELECT
        patient_id,
        count(*) AS condition_count,
        count(DISTINCT CASE
            WHEN is_chronic AND status = 'Active' AND condition_category <> 'Unmapped'
                THEN condition_category
        END) AS chronic_condition_count,
        bool_or(condition_category = 'Diabetes' AND status = 'Active') AS has_diabetes,
        bool_or(condition_category = 'Hypertension' AND status = 'Active') AS has_hypertension,
        bool_or(condition_category = 'Heart Failure' AND status = 'Active') AS has_heart_failure,
        bool_or(condition_category = 'COPD' AND status = 'Active') AS has_copd,
        bool_or(condition_category = 'Chronic Kidney Disease' AND status = 'Active') AS has_ckd
    FROM silver_conditions
    GROUP BY patient_id
)
SELECT
    p.patient_id,
    p.age_band,
    p.risk_category,
    coalesce(c.condition_count, 0) AS condition_count,
    coalesce(c.chronic_condition_count, 0) AS chronic_condition_count,
    CASE
        WHEN coalesce(c.chronic_condition_count, 0) = 0 THEN 'No active chronic conditions'
        WHEN c.chronic_condition_count = 1 THEN '1 chronic condition'
        WHEN c.chronic_condition_count <= 3 THEN '2-3 chronic conditions'
        ELSE '4+ chronic conditions'
    END AS multimorbidity_group,
    coalesce(c.has_diabetes, false) AS has_diabetes,
    coalesce(c.has_hypertension, false) AS has_hypertension,
    coalesce(c.has_heart_failure, false) AS has_heart_failure,
    coalesce(c.has_copd, false) AS has_copd,
    coalesce(c.has_ckd, false) AS has_ckd
FROM silver_patients AS p
LEFT JOIN conditions AS c USING (patient_id)
"""

SQL["dim_patient"] = """
-- Patient dimension for analytics. Direct identifiers (names, date of birth) are intentionally
-- excluded: Gold carries only what reporting needs.
SELECT
    p.patient_id,
    p.age,
    p.age_band,
    p.gender,
    p.race,
    p.city,
    p.state,
    p.insurance_type,
    p.risk_score,
    p.risk_category,
    ph.condition_count,
    ph.chronic_condition_count,
    ph.multimorbidity_group,
    ph.has_diabetes,
    ph.has_hypertension,
    ph.has_heart_failure,
    ph.has_copd,
    ph.has_ckd
FROM silver_patients AS p
INNER JOIN gold_population_health AS ph USING (patient_id)
"""

SQL["gold_encounter_summary"] = """
-- One row per encounter. Child tables are aggregated BEFORE joining so encounters and charges
-- are never multiplied by child rows.
WITH vitals AS (
    SELECT encounter_id, count(*) AS vital_sign_count
    FROM silver_vitals
    GROUP BY encounter_id
),
medications AS (
    SELECT encounter_id, count(*) AS medication_order_count
    FROM silver_medications
    GROUP BY encounter_id
)
SELECT
    e.encounter_id,
    e.patient_id,
    e.facility_id,
    e.encounter_date,
    e.discharge_date,
    e.encounter_year,
    e.encounter_month,
    e.encounter_type,
    e.department,
    e.primary_diagnosis_code,
    e.primary_diagnosis_description,
    e.discharge_disposition,
    e.length_of_stay_days,
    e.los_band,
    e.total_charges,
    e.is_inpatient,
    e.is_ed,
    coalesce(v.vital_sign_count, 0) AS vital_sign_count,
    coalesce(m.medication_order_count, 0) AS medication_order_count
FROM silver_encounters AS e
LEFT JOIN vitals AS v USING (encounter_id)
LEFT JOIN medications AS m USING (encounter_id)
"""

SQL["gold_financial"] = """
-- One row per claim. Rates are calculated from components in measures, never by averaging
-- row-level ratios. Total Paid Amount is paid claims, not recognized revenue.
SELECT
    c.claim_id,
    c.encounter_id,
    c.patient_id,
    e.facility_id,
    d.payer_key,
    c.claim_date,
    c.claim_amount,
    c.paid_amount,
    c.denied_amount,
    c.patient_responsibility,
    c.claim_status,
    c.is_denied,
    c.denial_reason,
    c.days_to_payment,
    c.payment_ratio
FROM silver_claims AS c
LEFT JOIN silver_encounters AS e ON e.encounter_id = c.encounter_id
LEFT JOIN dim_payer AS d ON d.payer = c.payer AND d.payer_type = c.payer_type
"""

SQL["gold_readmissions"] = """
-- One row per index inpatient encounter. SYNTHETIC DEMONSTRATION RULE, not a validated clinical
-- readmission specification:
--   * next qualifying admission = the next inpatient admission strictly after the index
--     discharge_date (no unrestricted self-join over every encounter pair);
--   * readmitted when that interval is 1 through 30 days inclusive;
--   * follow-up eligible when at least 30 days of observation remain before the cutoff
--     (the latest encounter_date in the dataset). Ineligible rows are kept and flagged so
--     measures can exclude them from BOTH numerator and denominator.
WITH inpatient AS (
    SELECT encounter_id, patient_id, facility_id, encounter_date AS admission_date, discharge_date
    FROM silver_encounters
    WHERE is_inpatient AND is_chronology_valid
),
cutoff AS (
    SELECT max(encounter_date) AS observation_cutoff FROM silver_encounters
),
with_next AS (
    SELECT
        i.*,
        (
            SELECT min(n.admission_date)
            FROM inpatient AS n
            WHERE n.patient_id = i.patient_id AND n.admission_date > i.discharge_date
        ) AS next_admission_date
    FROM inpatient AS i
)
SELECT
    w.encounter_id AS index_encounter_id,
    w.patient_id,
    w.facility_id,
    w.admission_date AS index_admission_date,
    w.discharge_date AS index_discharge_date,
    w.next_admission_date,
    datediff(w.next_admission_date, w.discharge_date) AS days_to_next_admission,
    coalesce(datediff(w.next_admission_date, w.discharge_date) BETWEEN 1 AND 30, false)
        AS is_readmitted_30d,
    w.discharge_date + 30 <= c.observation_cutoff AS is_followup_eligible,
    c.observation_cutoff
FROM with_next AS w
CROSS JOIN cutoff AS c
"""

SQL["gold_ed_utilization"] = """
-- One row per patient and calendar year with at least one ED visit. The frequent-use threshold
-- (4 or more ED visits in a year) is a synthetic analytical definition.
SELECT
    patient_id,
    encounter_year AS `year`,
    count(*) AS ed_visit_count,
    count(*) >= 4 AS is_frequent_ed_user
FROM silver_encounters
WHERE is_ed
GROUP BY patient_id, encounter_year
"""

SQL["gold_alos"] = """
-- One row per primary diagnosis and facility. Keeps count and total LOS so averages can be
-- re-aggregated correctly (never average grouped averages).
SELECT
    primary_diagnosis_code,
    any_value(primary_diagnosis_description) AS primary_diagnosis_description,
    facility_id,
    count(*) AS inpatient_count,
    sum(length_of_stay_days) AS total_los_days,
    round(sum(length_of_stay_days) / count(*), 2) AS average_los_days
FROM silver_encounters
WHERE is_inpatient
GROUP BY primary_diagnosis_code, facility_id
"""

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

for name, sql in SQL.items():
    if name in STAGING:
        spark.sql(sql).createOrReplaceTempView(name)
        continue
    persisted = write_table(spark.sql(sql), name)
    expected_rows = EXPECTED_GOLD_ROWS[name]
    check(f"{name}: rows equal baseline", persisted == expected_rows, f"{persisted} (baseline {expected_rows})")
    key_check(name, KEYS[name])

for gold, silver in ROW_PRESERVATION:
    g, s = spark.table(gold).count(), spark.table(silver).count()
    check(f"{gold}: row count equals {silver} (no multiplication or loss)", g == s, f"{gold} {g}, {silver} {s}")

for fact, fact_column, dimension, dimension_column in RELATIONSHIPS:
    missing = scalar(
        f"SELECT count(*) FROM `{fact}` AS f LEFT JOIN `{dimension}` AS d "
        f"ON f.`{fact_column}` = d.`{dimension_column}` "
        f"WHERE f.`{fact_column}` IS NOT NULL AND d.`{dimension_column}` IS NULL"
    )
    check(
        f"{fact}.{fact_column} -> {dimension}.{dimension_column}: no missing dimension keys",
        missing == 0,
        f"{missing} missing",
    )

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

actual = {
    "silver_claim_amount_total": scalar("SELECT sum(claim_amount) FROM silver_claims"),
    "gold_claim_amount_total": scalar(f"SELECT sum(claim_amount) FROM {CLAIMS}"),
    "silver_paid_amount_total": scalar("SELECT sum(paid_amount) FROM silver_claims"),
    "gold_paid_amount_total": scalar(f"SELECT sum(paid_amount) FROM {CLAIMS}"),
    "silver_total_charges": scalar("SELECT sum(total_charges) FROM silver_encounters"),
    "gold_total_charges": scalar(f"SELECT sum(total_charges) FROM {ENCOUNTERS}"),
}
for key, value in actual.items():
    expected_value = EXPECTED_RECONCILIATION[key]
    matches = abs(float(value) - float(expected_value)) < 0.005
    check(f"reconciliation {key}", matches, f"{value} (baseline {expected_value})")

numerator = scalar(f"SELECT count(*) FROM {READMISSIONS} WHERE is_followup_eligible AND is_readmitted_30d")
denominator = scalar(f"SELECT count(*) FROM {READMISSIONS} WHERE is_followup_eligible")
print(f"30-day readmissions (synthetic demonstration): {numerator} of {denominator} eligible index encounters")

finish()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
