// GENERATED by `ffia schemas export` from schemas/openapi.json. Do not edit by hand.

/** The agent's answer and how it was grounded. */
export interface AgentAnswer {
  readonly agent: string;
  readonly question: string;
  readonly answer: string;
  readonly tool_calls?: readonly ToolCall[];
  readonly grounded: boolean;
  readonly supported_questions?: readonly string[];
}

/** The outcome of one case. */
export interface AgentCaseResult {
  readonly id: string;
  readonly question: string;
  readonly passed: boolean;
  readonly grounded: boolean;
  readonly missing: readonly string[];
  readonly label: string;
  readonly answer_excerpt: string;
  readonly tools: readonly string[];
  readonly provider: string;
  readonly fallback_used: boolean;
}

/** All cases, the pass rate and the gate. */
export interface AgentEvalReport {
  readonly evaluation_id?: string;
  readonly suite: string;
  readonly provider: string;
  readonly labels: readonly string[];
  readonly fallback_cases: number;
  readonly compared: number;
  readonly passed: number;
  readonly pass_rate: number;
  readonly gate_passed: boolean;
  readonly status: "PASSED" | "FAILED";
  readonly cases: readonly AgentCaseResult[];
}

/** What the UI needs to ask an agent: who answers and which questions are evaluated. */
export interface AgentProfile {
  readonly agent: string;
  readonly suite: string;
  readonly dataset_profile: string;
  readonly local_provider: string;
  readonly live_provider: string | null;
  readonly suggested_questions: readonly string[];
}

/** A question for a named agent. */
export interface AgentQuestion {
  readonly agent?: string;
  readonly question: string;
}

/** A recorded approval, bound to the target's destination hash and time-limited. */
export interface Approval {
  readonly approval_id?: string;
  readonly change_id: string;
  readonly approver: string;
  readonly decision: ApprovalDecision;
  readonly comment: string;
  readonly destination_hash: string;
  readonly created_at?: string;
  readonly expires_at: string;
}

/** A human decision. */
export type ApprovalDecision = "APPROVED" | "REJECTED";

/** A human approval or rejection of a plan. */
export interface ApprovalRequest {
  readonly change_id: string;
  readonly approver: string;
  readonly decision: ApprovalDecision;
  readonly comment?: string;
}

/** A component of the reference architecture. */
export interface ArchitectureComponent {
  readonly id: string;
  readonly name: string;
  readonly layer: string;
  readonly status: "GA" | "PREVIEW" | "MIXED" | "DEPRECATED" | "UNKNOWN/NEEDS VALIDATION" | "LOCAL";
  readonly description: LevelText;
  readonly owns: readonly string[];
  readonly does_not_own?: readonly string[];
  readonly pattern_ids?: readonly string[];
  readonly offline_equivalent: string;
  readonly sources?: readonly string[];
}

/** A directed interaction between two components. */
export interface ArchitectureFlow {
  readonly id: string;
  readonly source: string;
  readonly target: string;
  readonly label: string;
  readonly kind: "context" | "reasoning" | "access" | "authority" | "evidence" | "fallback" | "change";
}

/** A layer of the reference architecture and the question it answers. */
export interface ArchitectureLayer {
  readonly id: string;
  readonly name: string;
  readonly question: string;
  readonly summary: string;
}

/** ``education/architecture/explorer.yaml``. */
export interface ArchitectureMap {
  readonly version: 1;
  readonly layers: readonly ArchitectureLayer[];
  readonly components: readonly ArchitectureComponent[];
  readonly flows?: readonly ArchitectureFlow[];
}

/** One catalog pattern (summary level). */
export interface ArchitecturePattern {
  readonly id: string;
  readonly name: string;
  readonly summary: string;
  readonly status: "GA" | "PREVIEW" | "MIXED";
  readonly preview_dependencies: readonly string[];
  readonly default_demo_path: "LOCAL" | "HYBRID" | "DOCUMENTATION";
  readonly when_to_use: string;
  readonly when_not_to_use: string;
  readonly fabric_role: string;
  readonly foundry_role: string;
  readonly mcp_role: string;
  readonly authority: string;
  readonly offline_equivalent: string;
  readonly selection_signals: readonly string[];
  readonly sources: readonly string[];
}

/** One audit entry. */
export interface AuditRecord {
  readonly audit_id?: string;
  readonly correlation_id: string;
  readonly timestamp?: string;
  readonly actor: string;
  readonly action: string;
  readonly capability: string;
  readonly requested_provider: string;
  readonly selected_provider: string;
  readonly operating_mode: OperatingMode;
  readonly execution_label: ExecutionLabel;
  readonly cloud_operation_performed: boolean;
  readonly success: boolean;
  readonly duration_ms?: number | null;
  readonly fallback_used?: boolean;
  readonly fallback_reason?: string | null;
  readonly change_id?: string | null;
  readonly approval_id?: string | null;
  readonly tool?: string | null;
  readonly details?: Readonly<Record<string, string | number | boolean | null>>;
}

/** A rectangle in diagram coordinates. */
export interface Box {
  readonly x: number;
  readonly y: number;
  readonly w: number;
  readonly h: number;
}

/** Circuit breaker state. */
export type BreakerState = "CLOSED" | "OPEN" | "HALF_OPEN";

/** A point-in-time view of a breaker. */
export interface BreakerStatus {
  readonly name: string;
  readonly state: BreakerState;
  readonly consecutive_failures: number;
  readonly failure_threshold: number;
  readonly last_failure_reason: string | null;
}

/** Where a draft ends: ready for a human, or held by the gate. */
export type BriefStatus = "READY FOR APPROVAL" | "HELD";

/** A capability and how it is currently served. */
export interface Capability {
  readonly name: string;
  readonly description: string;
  readonly served_by: string;
}

/** A request to plan a change (from a person, an agent or an MCP tool). */
export interface ChangeRequest {
  readonly operation: string;
  readonly target: FabricTarget;
  readonly reason: string;
  readonly requested_by: string;
}

/** Lifecycle of a change. */
export type ChangeStatus = "PROPOSED" | "BLOCKED" | "APPROVED" | "REJECTED" | "EXECUTED" | "VERIFIED" | "FAILED";

/** A learner's answer to one knowledge check. */
export interface CheckAnswer {
  readonly choice: number;
}

/** Whether the answer was correct, with the explanation. */
export interface CheckGrade {
  readonly check_id: string;
  readonly correct: boolean;
  readonly correct_choice: number;
  readonly explanation: string;
}

/** One readiness line. */
export interface CheckLine {
  readonly component: string;
  readonly status: string;
  readonly detail: string;
}

/** The outcome of one deterministic validation check. */
export interface CheckResult {
  readonly name: string;
  readonly passed: boolean;
  readonly detail: string;
  readonly category?: EvidenceCategory;
}

/** Where a passage came from. */
export interface Citation {
  readonly document: string;
  readonly title: string;
  readonly section: string;
  readonly path: string;
}

/** A column name and type. */
export interface ColumnInfo {
  readonly name: string;
  readonly data_type: string;
}

/** The coverage of one question. */
export interface CompletenessItem {
  readonly id: string;
  readonly question: string;
  readonly answered: boolean;
  readonly answered_by: readonly string[];
  readonly planned_phase: number | null;
}

/** Coverage of the completeness gate. */
export interface CompletenessReport {
  readonly total: number;
  readonly answered: number;
  readonly coverage: number;
  readonly items: readonly CompletenessItem[];
}

/** A glossary term taught by a lesson. */
export interface Concept {
  readonly term: string;
  readonly definition: string;
}

/** Readiness of every demo component and the recommended mode. */
export interface DemoCheckReport {
  readonly lines: readonly CheckLine[];
  readonly recommended_mode: OperatingMode;
  readonly reason: string;
}

/** One act of the scripted demo. */
export interface DemoStep {
  readonly act: number;
  readonly title: string;
  readonly required: boolean;
  readonly passed: boolean;
  readonly label: string;
  readonly summary: string;
  readonly evidence?: readonly string[];
}

/** A cross-cutting rule drawn as a band under the diagram (identity, policy, evidence…). */
export interface DiagramBand {
  readonly id: string;
  readonly kind: "identity" | "policy" | "evidence" | "failure" | "network";
  readonly text: string;
  readonly step?: string | null;
}

/** A directed arrow between two nodes. */
export interface DiagramEdge {
  readonly id: string;
  readonly source: string;
  readonly target: string;
  readonly label?: string;
  readonly kind: "context" | "reasoning" | "access" | "authority" | "evidence" | "fallback" | "change" | "data" | "config";
  readonly step?: string | null;
  readonly planned?: boolean;
}

/** A box on the diagram. */
export interface DiagramNode {
  readonly id: string;
  readonly label: string;
  readonly sublabel?: string;
  readonly kind: "person" | "client" | "harness" | "knowledge" | "app" | "service" | "foundry" | "fabric" | "data" | "mcp" | "gateway" | "identity" | "policy" | "evidence" | "local" | "external";
  readonly state: "implemented" | "planned" | "documented" | "preview" | "tenant-validation" | "optional";
  readonly col: number;
  readonly row: number;
  readonly width?: number;
  readonly step?: string | null;
  readonly component?: string | null;
  readonly summary?: string;
  readonly repo_path?: string | null;
  readonly phase?: number | null;
  readonly runtime?: "agents" | "api" | "mcp" | "fabric-local" | "fabric-live" | "foundry" | "changes" | "audit" | "education" | "evaluation" | "router" | null;
  readonly icon?: string | null;
  readonly sources?: readonly string[];
}

/** One build-up step of a whiteboard view. */
export interface DiagramStep {
  readonly id: string;
  readonly label: string;
  readonly cue: string;
}

/** A request followed one hop at a time. */
export interface DiagramTrace {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly label: "PLANNED FLOW" | "LOCAL" | "SIMULATED" | "PREVIEW" | "DOCUMENTED";
  readonly demo_act?: number | null;
  readonly steps: readonly TraceStep[];
}

/** ``education/architecture/views/<id>.yaml``. */
export interface DiagramView {
  readonly id: string;
  readonly title: string;
  readonly kind: "reference" | "system" | "topology" | "flow" | "maturity" | "resilience";
  readonly summary: string;
  readonly cue: string;
  readonly columns: number;
  readonly rows: number;
  readonly aligned_to?: readonly string[];
  readonly pattern_ids?: readonly string[];
  readonly doc?: string | null;
  readonly steps?: readonly DiagramStep[];
  readonly zones?: readonly DiagramZone[];
  readonly nodes: readonly DiagramNode[];
  readonly edges?: readonly DiagramEdge[];
  readonly bands?: readonly DiagramBand[];
  readonly traces?: readonly DiagramTrace[];
}

/** A labeled region (trust boundary, tenant, local machine, optional add-on). */
export interface DiagramZone {
  readonly id: string;
  readonly label: string;
  readonly kind: "local" | "tenant" | "fabric" | "foundry" | "github" | "optional" | "offline";
  readonly col: number;
  readonly row: number;
  readonly cols: number;
  readonly rows: number;
  readonly step?: string | null;
}

/** A routed edge: the full polyline (endpoints included) and its label anchor. */
export interface EdgePath {
  readonly points: readonly (readonly [number, number])[];
  readonly label_at: readonly [number, number];
  readonly label_fraction: number;
}

/** Evaluate declared measures. */
export interface EvaluateMeasures {
  readonly operation: "evaluate_measures";
  readonly semantic_model_id: string;
  readonly measures?: readonly string[] | null;
}

/** Evaluate observed measure values (or the local provider's values) against the baseline. */
export interface EvaluationRequest {
  readonly profile: string;
  readonly observed?: Readonly<Record<string, number | null>> | null;
  readonly observed_label?: "LIVE" | "HYBRID" | "LOCAL" | "MOCKED";
}

/** Outcome of an evaluation run. */
export interface EvaluationResult {
  readonly evaluation_id?: string;
  readonly profile: string;
  readonly observed_values_source: "local-provider" | "caller-supplied";
  readonly observed_label: string;
  readonly tolerance: number;
  readonly compared: number;
  readonly passed: number;
  readonly pass_rate: number;
  readonly gate_passed: boolean;
  readonly comparisons: readonly MeasureComparison[];
  readonly missing_measures: readonly string[];
  readonly unexpected_measures: readonly string[];
}

/** A single piece of evidence attached to a result. */
export interface Evidence {
  readonly category: EvidenceCategory;
  readonly statement: string;
  readonly reference?: string | null;
}

/** How strongly a statement is supported. Used to keep teaching claims honest. */
export type EvidenceCategory = "SIMULATED LOCALLY" | "DOCUMENTED FABRIC BEHAVIOR" | "DOCUMENTED BEHAVIOR" | "REQUIRES TENANT VALIDATION" | "ASSUMPTION" | "PRODUCTION RECOMMENDATION" | "PREVIEW LIMITATION" | "VERIFIED LIVE";

/** A claim with how strongly it is supported (keeps teaching honest). */
export interface EvidenceClaim {
  readonly statement: string;
  readonly category: EvidenceCategory;
  readonly sources?: readonly string[];
}

/** A request to execute an approved plan. */
export interface ExecuteRequest {
  readonly change_id: string;
  readonly approval_id: string;
  readonly executed_by: string;
}

/** ExecutionEnvelope[AgentAnswer] */
export interface ExecutionEnvelope_AgentAnswer_ {
  readonly operating_mode: OperatingMode;
  readonly execution_label: ExecutionLabel;
  readonly requested_provider: string;
  readonly selected_provider: string;
  readonly cloud_operation_performed: boolean;
  readonly equivalent_fabric_service: string;
  readonly teaching_objective: string;
  readonly data: AgentAnswer;
  readonly correlation_id?: string;
  readonly timestamp?: string;
  readonly fallback_used?: boolean;
  readonly fallback_reason?: string | null;
  readonly simulation_notice?: string | null;
  readonly evidence?: readonly Evidence[];
}

/** ExecutionEnvelope[KnowledgeResult] */
export interface ExecutionEnvelope_KnowledgeResult_ {
  readonly operating_mode: OperatingMode;
  readonly execution_label: ExecutionLabel;
  readonly requested_provider: string;
  readonly selected_provider: string;
  readonly cloud_operation_performed: boolean;
  readonly equivalent_fabric_service: string;
  readonly teaching_objective: string;
  readonly data: KnowledgeResult;
  readonly correlation_id?: string;
  readonly timestamp?: string;
  readonly fallback_used?: boolean;
  readonly fallback_reason?: string | null;
  readonly simulation_notice?: string | null;
  readonly evidence?: readonly Evidence[];
}

/** ExecutionEnvelope[object] */
export interface ExecutionEnvelope_object_ {
  readonly operating_mode: OperatingMode;
  readonly execution_label: ExecutionLabel;
  readonly requested_provider: string;
  readonly selected_provider: string;
  readonly cloud_operation_performed: boolean;
  readonly equivalent_fabric_service: string;
  readonly teaching_objective: string;
  readonly data: unknown;
  readonly correlation_id?: string;
  readonly timestamp?: string;
  readonly fallback_used?: boolean;
  readonly fallback_reason?: string | null;
  readonly simulation_notice?: string | null;
  readonly evidence?: readonly Evidence[];
}

/** How a single result was produced. */
export type ExecutionLabel = "LIVE" | "HYBRID" | "LOCAL" | "SIMULATED" | "MOCKED" | "PREVIEW" | "UNAVAILABLE";

/** What happened when an approved change was executed and verified. */
export interface ExecutionResult {
  readonly change_id: string;
  readonly approval_id: string;
  readonly status: ChangeStatus;
  readonly execution_label: ExecutionLabel;
  readonly verification: CheckResult;
  readonly rollback: string;
}

/** What a change applies to. Workspaces are referenced by overlay alias, never by ID. */
export interface FabricTarget {
  readonly workspace_alias: string;
  readonly item_type: "Lakehouse" | "Notebook" | "SemanticModel" | "Report";
  readonly item_name: string;
  readonly destination: "LOCAL" | "LIVE";
}

/** The labeled local equivalent an agent may use when the step's primary tool is unavailable. */
export interface Fallback {
  readonly server?: "ffia-local";
  readonly tools: readonly string[];
  readonly label: "LOCAL" | "SIMULATED";
  readonly note?: string;
}

/** Return a semantic model. */
export interface GetSemanticModel {
  readonly operation: "get_semantic_model";
  readonly semantic_model_id: string;
}

/** Sanitized provenance. Never names, titles, authors, identifiers or URLs. */
export interface GuideProvenance {
  readonly derived_from: "customer engagement guide (sanitized)" | "original";
  readonly sanitized_on: string;
  readonly denylist_ref: string;
}

/** One step with prompts, checkpoint and the evidence that proves it. */
export interface GuideStep {
  readonly id: string;
  readonly title: string;
  readonly objective: string;
  readonly copilot_prompt: string;
  readonly claude_code_prompt: string;
  readonly tool_path: ToolPath;
  readonly skills?: readonly string[];
  readonly writes: boolean;
  readonly approval_required: boolean;
  readonly checkpoint: string;
  readonly evidence_required: readonly string[];
  readonly not_evidence?: readonly string[];
  readonly offline_equivalent: string;
  readonly offline_command?: string | null;
  readonly failure_modes?: readonly string[];
  readonly requires_windows?: boolean;
  readonly rehearsal?: Rehearsal | null;
  readonly diagram_focus?: readonly string[];
}

/** HTTPValidationError */
export interface HTTPValidationError {
  readonly detail?: readonly ValidationError[];
}

/** Liveness. */
export interface Health {
  readonly status: string;
}

/** An item in a workspace. */
export interface ItemInfo {
  readonly id: string;
  readonly display_name: string;
  readonly type: "Lakehouse" | "SemanticModel";
  readonly workspace_id: string;
  readonly description: string;
}

/** A question for the knowledge base. */
export interface KnowledgeQuery {
  readonly question: string;
  readonly top?: number;
}

/** Passages for a question, or why retrieval is unavailable. */
export interface KnowledgeResult {
  readonly knowledge_base: string;
  readonly question: string;
  readonly preview_flag: string;
  readonly enabled: boolean;
  readonly passages: readonly Passage[];
  readonly note: string;
}

/** ``education/labs/<id>/lab.yaml``. */
export interface Lab {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly level: "executive" | "l100" | "l200" | "l300" | "l400";
  readonly duration_minutes: number;
  readonly mode: "OFFLINE" | "HYBRID" | "LIVE";
  readonly pattern_ids?: readonly string[];
  readonly lessons?: readonly string[];
  readonly prerequisites?: readonly string[];
  readonly steps: readonly LabStep[];
}

/** One stage of a lab. */
export interface LabStep {
  readonly stage: "LEARN" | "SEE" | "BUILD" | "INSPECT" | "BREAK IT" | "RECOVER" | "VERIFY" | "GO DEEPER" | "TRY WITH COPILOT" | "TRY WITH CLAUDE CODE" | "PRODUCTION NOTES";
  readonly title: string;
  readonly instructions: string;
  readonly commands?: readonly string[];
  readonly expected?: string | null;
  readonly evidence_category?: EvidenceCategory | null;
}

/** A lab in a list. */
export interface LabSummary {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly level: "executive" | "l100" | "l200" | "l300" | "l400";
  readonly duration_minutes: number;
  readonly mode: "OFFLINE" | "HYBRID" | "LIVE";
  readonly pattern_ids: readonly string[];
  readonly lessons: readonly string[];
}

/** A lesson in a list. */
export interface LessonSummary {
  readonly id: string;
  readonly area: string;
  readonly title: string;
  readonly summary: string;
  readonly status: "GA" | "PREVIEW" | "MIXED" | "DEPRECATED" | "UNKNOWN/NEEDS VALIDATION" | "LOCAL";
  readonly pattern_ids: readonly string[];
  readonly related_labs: readonly string[];
  readonly related_guides: readonly string[];
}

/** A full lesson for the reader, with checks but no answers. */
export interface LessonView {
  readonly id: string;
  readonly area: string;
  readonly title: string;
  readonly summary: string;
  readonly status: "GA" | "PREVIEW" | "MIXED" | "DEPRECATED" | "UNKNOWN/NEEDS VALIDATION" | "LOCAL";
  readonly pattern_ids: readonly string[];
  readonly related_labs: readonly string[];
  readonly related_guides: readonly string[];
  readonly learning_objectives: readonly string[];
  readonly prerequisites: readonly string[];
  readonly concepts: readonly Concept[];
  readonly evidence: readonly EvidenceClaim[];
  readonly try_it: readonly TryIt[];
  readonly copilot_prompt: string;
  readonly claude_code_prompt: string;
  readonly production_notes: readonly string[];
  readonly sources: readonly string[];
  readonly levels: readonly LevelBody[];
  readonly checks: readonly PublicCheck[];
}

/** The Markdown body of one level. */
export interface LevelBody {
  readonly level: "executive" | "l100" | "l200" | "l300" | "l400";
  readonly label: string;
  readonly markdown: string;
}

/** A short description per level. */
export interface LevelText {
  readonly executive: string;
  readonly l100: string;
  readonly l200: string;
  readonly l300: string;
  readonly l400: string;
}

/** List items in a workspace. */
export interface ListItems {
  readonly operation: "list_items";
  readonly workspace_id: string;
}

/** List tables in a lakehouse. */
export interface ListTables {
  readonly operation: "list_tables";
  readonly lakehouse_id: string;
}

/** List workspaces. */
export interface ListWorkspaces {
  readonly operation: "list_workspaces";
}

/** One measure compared with its expected value. */
export interface MeasureComparison {
  readonly name: string;
  readonly expected: number | null;
  readonly observed: number | null;
  readonly absolute_difference: number | null;
  readonly passed: boolean;
}

/** The value of one semantic-model measure. */
export interface MeasureValue {
  readonly name: string;
  readonly display_name: string;
  readonly value: number | null;
  readonly format: string;
  readonly synthetic_demonstration: boolean;
}

/** Which teams to brief; all teams by default. */
export interface MonthlyInsightsRequest {
  readonly teams?: readonly string[];
}

/** The result of one workflow run. Nothing was delivered. */
export interface MonthlyInsightsRun {
  readonly run_id?: string;
  readonly workflow: string;
  readonly engine: string;
  readonly dataset_profile: string;
  readonly observation_month: string;
  readonly steps: readonly string[];
  readonly max_concurrency: number;
  readonly drafts: readonly TeamBriefDraft[];
  readonly ready: number;
  readonly held: number;
  readonly labels: readonly string[];
  readonly delivery: string;
  readonly synthetic_notice: string;
}

/** The live state of one diagram node. */
export interface NodeRuntime {
  readonly node: string;
  readonly binding: "agents" | "api" | "mcp" | "fabric-local" | "fabric-live" | "foundry" | "changes" | "audit" | "education" | "evaluation" | "router";
  readonly status: "ACTIVE" | "READY" | "DEGRADED" | "UNAVAILABLE" | "NOT CONFIGURED";
  readonly label: string;
  readonly detail: string;
}

/** Outcome of the offline demo (a release gate). */
export interface OfflineDemoReport {
  readonly passed: boolean;
  readonly operating_mode: OperatingMode;
  readonly steps: readonly DemoStep[];
  readonly label_counts: Readonly<Record<string, number>>;
  readonly live_operations: number;
  readonly cloud_operations: number;
}

/** How the system as a whole is running. */
export type OperatingMode = "LIVE" | "HYBRID" | "OFFLINE";

/** One retrieved section and its score. */
export interface Passage {
  readonly text: string;
  readonly score: number;
  readonly citation: Citation;
}

/** A validated change plan. Nothing has executed. */
export interface ProposedChange {
  readonly change_id?: string;
  readonly correlation_id: string;
  readonly operation: string;
  readonly target: FabricTarget;
  readonly provider: string;
  readonly reason: string;
  readonly requested_by: string;
  readonly risk: "low" | "medium" | "high";
  readonly reversible: boolean;
  readonly expected_impact: string;
  readonly validation: readonly string[];
  readonly rollback: string;
  readonly approval_required: boolean;
  readonly policy_allowed: boolean;
  readonly policy_reasons: readonly string[];
  readonly precondition: CheckResult;
  readonly destination_hash: string;
  readonly status: ChangeStatus;
  readonly created_at?: string;
}

/** One provider and its readiness. */
export interface ProviderStatus {
  readonly capability: string;
  readonly name: string;
  readonly kind: "LIVE" | "LOCAL" | "FAULT-INJECTION" | "NOT AVAILABLE";
  readonly configured: boolean;
  readonly ready: boolean;
  readonly note: string;
}

/** A knowledge check without its answer. */
export interface PublicCheck {
  readonly id: string;
  readonly level: "executive" | "l100" | "l200" | "l300" | "l400";
  readonly question: string;
  readonly choices: readonly string[];
}

/** Preview a table (bounded). */
export interface ReadTable {
  readonly operation: "read_table";
  readonly lakehouse_id: string;
  readonly table: string;
  readonly limit?: number;
}

/** Readiness with the checks behind it. */
export interface Readiness {
  readonly ready: boolean;
  readonly checks: Readonly<Record<string, boolean>>;
}

/** Needs from the selection vocabulary. */
export interface RecommendRequest {
  readonly needs: readonly string[];
  readonly include_preview?: boolean;
}

/** A ranked pattern recommendation with its reasons. */
export interface Recommendation {
  readonly pattern_id: string;
  readonly name: string;
  readonly score: number;
  readonly matched_needs: readonly string[];
  readonly status: "GA" | "PREVIEW" | "MIXED";
  readonly preview_dependencies: readonly string[];
  readonly default_demo_path: string;
  readonly why: string;
}

/** Outcome of the recovery drill. */
export interface RecoveryReport {
  readonly scenario: string;
  readonly table: string;
  readonly steps: readonly RecoveryStep[];
  readonly recovered: boolean;
  readonly counterfactual_recoverable: boolean;
  readonly duplicates_detected: number;
  readonly snapshot: SnapshotManifest;
  readonly scale: ScaleEstimate;
}

/** One narrated step of the drill. */
export interface RecoveryStep {
  readonly name: string;
  readonly day: number | null;
  readonly summary: string;
  readonly category: EvidenceCategory;
  readonly checks?: readonly CheckResult[];
}

/** The governed change a write step can rehearse against the simulated workspace. */
export interface Rehearsal {
  readonly operation: string;
  readonly item_type: "Lakehouse" | "Notebook" | "SemanticModel" | "Report";
  readonly item_name: string;
  readonly note?: string;
}

/** A view with the shared layout used by both the app and the draw.io files. */
export interface RenderedView {
  readonly view: DiagramView;
  readonly layout: ViewLayout;
}

/** Why a request went where it went. */
export interface RouteDecision {
  readonly capability: string;
  readonly operation: string;
  readonly correlation_id: string;
  readonly timestamp?: string;
  readonly requested_provider: string;
  readonly selected_provider: string;
  readonly operating_mode: OperatingMode;
  readonly outcome: "LIVE" | "LOCAL" | "FALLBACK" | "UNAVAILABLE";
  readonly attempts: number;
  readonly failure_reason?: string | null;
  readonly fallback_reason?: string | null;
  readonly breaker_state?: BreakerState | null;
}

/** Execution state shown everywhere (never implies a live connection that does not exist). */
export interface RuntimeStatus {
  readonly operating_mode: OperatingMode;
  readonly environment: string;
  readonly overlay: string;
  readonly data_provider: string;
  readonly agent_provider: string;
  readonly mcp: string;
  readonly identity: string;
  readonly write_mode: string;
  readonly preview_features: readonly string[];
  readonly providers: readonly ProviderStatus[];
  readonly breakers: readonly BreakerStatus[];
  readonly recent_route_decisions: readonly RouteDecision[];
  readonly built_profiles: readonly string[];
}

/** Extrapolated sizes for the conceptual table. Estimates, not measurements. */
export interface ScaleEstimate {
  readonly local_rows: number;
  readonly local_snapshot_bytes: number;
  readonly conceptual_rows: number;
  readonly estimated_snapshot_gib: number;
  readonly estimated_daily_change_rows: number;
  readonly note: string;
}

/** One need from the pattern-selection vocabulary. */
export interface SelectionSignal {
  readonly id: string;
  readonly description: string;
}

/** Metadata describing one full snapshot. */
export interface SnapshotManifest {
  readonly snapshot_id: string;
  readonly table: string;
  readonly created_day: number;
  readonly watermark_sequence: number;
  readonly row_count: number;
  readonly content_hash: string;
  readonly key_columns: readonly string[];
  readonly columns: readonly string[];
  readonly file: string;
  readonly size_bytes: number;
}

/** A lakehouse table. */
export interface TableInfo {
  readonly name: string;
  readonly layer: string;
  readonly row_count: number | null;
  readonly columns: readonly ColumnInfo[];
}

/** A bounded preview of table rows. */
export interface TablePreview {
  readonly table: string;
  readonly layer: string;
  readonly columns: readonly ColumnInfo[];
  readonly rows: readonly (Readonly<Record<string, string | number | boolean | null>>)[];
  readonly total_rows: number;
  readonly truncated: boolean;
}

/** One team's draft brief and the gate's verdict. */
export interface TeamBriefDraft {
  readonly team_id: string;
  readonly team_name: string;
  readonly question: string;
  readonly answer: string;
  readonly label: string;
  readonly provider: string;
  readonly fallback_used: boolean;
  readonly grounded: boolean;
  readonly expected: readonly string[];
  readonly missing: readonly string[];
  readonly status: BriefStatus;
  readonly reason: string;
  readonly correlation_id: string;
}

/** One tool the agent used, as reported by the agent runtime. */
export interface ToolCall {
  readonly name: string;
  readonly summary?: string;
}

/** The provider, server and tool a step must use. Substitution is not allowed. */
export interface ToolPath {
  readonly provider: string;
  readonly server?: string | null;
  readonly tools?: readonly string[];
  readonly substitution_allowed?: boolean;
  readonly fallback?: Fallback | null;
}

/** A tool, server, extension or service the guide needs. */
export interface ToolRequirement {
  readonly name: string;
  readonly purpose: string;
  readonly version?: string | null;
  readonly status: "GA" | "PREVIEW" | "OSS" | "UNKNOWN/NEEDS VALIDATION";
  readonly install: string;
  readonly required?: boolean;
}

/** One hop of a traced request. */
export interface TraceStep {
  readonly node: string;
  readonly edge?: string | null;
  readonly say: string;
  readonly note?: string;
}

/** An offline command the learner can run, and the label its result carries. */
export interface TryIt {
  readonly label: string;
  readonly command: string;
  readonly result_label: "LOCAL" | "SIMULATED" | "HYBRID" | "PREVIEW" | "UNAVAILABLE";
}

/** A Use-Case Guide (``guides/<id>/guide.yaml``). */
export interface UseCaseGuide {
  readonly id: string;
  readonly title: string;
  readonly industry: string;
  readonly scenario: string;
  readonly summary: string;
  readonly version: string;
  readonly status: "draft" | "validated-offline" | "validated-live";
  readonly provenance: GuideProvenance;
  readonly patterns: readonly string[];
  readonly maturity_levels: readonly ("L0" | "L1" | "L2" | "L3" | "L4" | "L5" | "L6")[];
  readonly harnesses: readonly ("copilot-vscode" | "copilot-cli" | "copilot-app" | "copilot-cloud-agent" | "claude-code")[];
  readonly operating_rules: readonly string[];
  readonly tools: readonly ToolRequirement[];
  readonly tenant_settings?: readonly string[];
  readonly os_constraints?: readonly string[];
  readonly dataset_profile: string;
  readonly expected_baseline: string;
  readonly diagram?: string | null;
  readonly steps: readonly GuideStep[];
}

/** ValidationError */
export interface ValidationError {
  readonly loc: readonly (string | number)[];
  readonly msg: string;
  readonly type: string;
  readonly input?: unknown;
  readonly ctx?: Readonly<Record<string, unknown>>;
}

/** Geometry for every node, zone and edge of a view. */
export interface ViewLayout {
  readonly width: number;
  readonly height: number;
  readonly grid_bottom: number;
  readonly nodes: Readonly<Record<string, Box>>;
  readonly zones: Readonly<Record<string, Box>>;
  readonly edges: Readonly<Record<string, EdgePath>>;
}

/** The runtime overlay for one view. */
export interface ViewRuntime {
  readonly view_id: string;
  readonly operating_mode: OperatingMode;
  readonly observed_at: string;
  readonly nodes: readonly NodeRuntime[];
}

/** An architecture view in a list. */
export interface ViewSummary {
  readonly id: string;
  readonly title: string;
  readonly kind: string;
  readonly summary: string;
  readonly doc: string | null;
  readonly pattern_ids: readonly string[];
}

/** A workspace visible to the provider. */
export interface WorkspaceInfo {
  readonly id: string;
  readonly display_name: string;
  readonly description: string;
}
