# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {}
# META }

# MARKDOWN ********************

# # MCP_01_Bronze: land the raw CSVs as Bronze Delta tables
#
# **Synthetic data only.** Use-Case Guide HC-01 profile: seven CSV sources whose row counts and structural quirks match the guide's documented baseline.
#
# Reads the seven CSVs from `Files/raw` and writes `bronze_` tables with lineage columns.
#
# Design choice to compare in INSPECT: the lab prompt asks for `inferSchema`. This reference reads
# every column as **string** so Bronze preserves source values exactly (no silent date or number
# coercion). Silver applies explicit, reviewed types. `multiLine` and the double-quote escape keep the
# quoted notes intact; the literal `\n` text and blank condition `encounter_id` values are preserved.
#
# - Attach the default lakehouse (for example `healthcare_lakehouse`) before running. No workspace or
#   lakehouse ID is stored in this definition.
# - Generated by `ffia notebooks render` from the same SQL the offline build runs on DuckDB. Do not
#   hand-edit; change the SQL and re-render.
# - A run in the portal or editor is not an MCP job. Evidence is the printed checks and read-back counts.

# PARAMETERS CELL ********************

PROFILE = "hc-lab-7file-v1"
RAW_PATH = "Files/raw"
TABLE_FORMAT = "delta"
EXPECTED_RAW_ROWS = {
    "claims": 1025,
    "clinical_notes": 150,
    "conditions": 428,
    "encounters": 1025,
    "medications": 643,
    "patients": 200,
    "vitals": 4299
}

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

from pyspark.sql import functions as F

CHECKS: list[tuple[str, bool, str]] = []


def check(name: str, passed: bool, detail: str) -> None:
    """Record and print one validation result."""
    CHECKS.append((name, passed, detail))
    print(f"[{'PASS' if passed else 'FAIL'}] {name}: {detail}")


def write_table(df, name: str) -> int:
    """Overwrite one table and return the persisted (read-back) row count."""
    (
        df.write.format(TABLE_FORMAT)
        .mode("overwrite")
        .option("overwriteSchema", "true")
        .saveAsTable(name)
    )
    return spark.table(name).count()


def scalar(sql: str):
    """Return the single value of a one-row, one-column query."""
    return spark.sql(sql).collect()[0][0]


def key_check(table: str, keys: list[str]) -> None:
    """Keys are populated and unique."""
    cols = ", ".join(f"`{k}`" for k in keys)
    populated = " AND ".join(f"`{k}` IS NOT NULL" for k in keys)
    total = scalar(f"SELECT count(*) FROM `{table}`")
    distinct = scalar(f"SELECT count(DISTINCT {cols}) FROM `{table}` WHERE {populated}")
    filled = scalar(f"SELECT count(*) FROM `{table}` WHERE {populated}")
    check(
        f"{table}: key ({', '.join(keys)}) populated and unique",
        total == distinct == filled,
        f"rows {total}, distinct keys {distinct}, populated keys {filled}",
    )


def finish() -> None:
    """Stop the run if any check failed, so a failed layer is never reported as built."""
    failed = [name for name, passed, _ in CHECKS if not passed]
    if failed:
        raise AssertionError(f"{len(failed)} check(s) failed: {failed}")
    print(f"All {len(CHECKS)} checks passed.")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def read_raw(table: str):
    """Read one CSV as strings, failing on malformed rows instead of dropping them."""
    return (
        spark.read.option("header", True)
        .option("multiLine", True)
        .option("quote", '"')
        .option("escape", '"')
        .option("mode", "FAILFAST")
        .csv(f"{RAW_PATH}/{table}.csv")
    )


for table, expected_rows in EXPECTED_RAW_ROWS.items():
    df = read_raw(table)
    parsed = df.count()
    check(
        f"bronze_{table}: parsed rows equal source baseline",
        parsed == expected_rows,
        f"parsed {parsed}, expected {expected_rows}",
    )
    if parsed != expected_rows:
        continue  # never write a table whose parse does not match the baseline
    lineage = df.withColumn("_source_file", F.lit(f"raw/{PROFILE}/{table}.csv")).withColumn(
        "_ingested_at", F.current_timestamp()
    )
    persisted = write_table(lineage, f"bronze_{table}")
    check(f"bronze_{table}: persisted rows equal parsed rows", persisted == parsed, f"persisted {persisted}")

finish()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
